# Pre-commit hooks configuration
# Install: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  # Python formatting with Black (matches CI)
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        files: ^(api|ingest)/.*\.py$
        args: [--line-length=100]

  # Import sorting with isort (matches CI)
  - repo: https://github.com/PyCQA/isort
    rev: 6.1.0
    hooks:
      - id: isort
        files: ^(api|ingest)/.*\.py$
        args: [--profile=black, --line-length=100]

  # Auto-fix unused imports and variables
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        files: ^(api|ingest)/.*\.py$
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports

  # Linting with Flake8 (matches CI) - runs after auto-fixes
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        files: ^(api|ingest)/.*\.py$
        args:
          - --max-line-length=100
          - --extend-ignore=E203,E501,W503

  # TypeScript/JavaScript formatting with Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^ui/.*\.(ts|tsx|js|jsx|json|css|md)$
        exclude: node_modules
        additional_dependencies:
          - prettier@3.1.0
