services:
  # React Frontend - Development
  frontend-dev:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./ui:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - app-network

  # Python API - Development
  api-dev:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    environment:
      - PORT=8000
      - DEBUG=1
    volumes:
      - ./api:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
