version: '3.8'

services:
  # React Frontend - Development
  frontend-dev:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./ui:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - app-network

  # Python Backend - Development (placeholder)
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=development
      - DEBUG=1
    volumes:
      - ./backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
