services:
  # React Frontend
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - app-network

  # Python API (placeholder for future implementation)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=production
    networks:
      - app-network
    # Uncomment when API is implemented
    # volumes:
    #   - ./api:/app
    #   - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  api_data:
