version: '3.8'

services:
  # React Frontend
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  # Python Backend (placeholder for future implementation)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=production
    networks:
      - app-network
    # Uncomment when backend is implemented
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
