name: CI

on:
  push:
    branches: [ "*" ]  # Trigger on all branches
  pull_request:
    branches: [ "*" ]  # Trigger on PRs to all branches

jobs:
  # UI Tests
  ui-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json

    - name: Install UI dependencies
      run: cd ui && npm ci

    - name: Run UI linting
      run: make lint-ui

    - name: Check UI formatting
      run: make format-check-ui

    - name: Check TypeScript compilation
      run: make check

    - name: Run UI tests
      run: make test-ui

    - name: Upload UI coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./ui/coverage/lcov.info
        flags: ui
        name: ui-coverage

  # API Tests
  api-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: api/pyproject.toml

    - name: Install API dependencies
      run: cd api && make dev-install

    - name: Check API code formatting
      run: cd api && make format-check

    - name: Run API linting
      run: cd api && make lint

    - name: Run API security scanning
      run: cd api && make security

    - name: Run API tests
      env:
        OPENAI_API_KEY: test-key
        PINECONE_API_KEY: test-key
        PINECONE_ENVIRONMENT: test-env
      run: cd api && make test

    - name: Upload API coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./api/coverage.xml
        flags: api
        name: api-coverage

  # Ingest Tests
  ingest-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: ingest/pyproject.toml

    - name: Install ingest dependencies
      run: cd ingest && make dev-install

    - name: Run ingest linting and formatting checks
      run: cd ingest && make lint

    - name: Run ingest code formatting check
      run: cd ingest && make format-check

    - name: Run ingest security scanning
      run: cd ingest && make security

    - name: Run ingest tests
      run: cd ingest && make test

    - name: Upload ingest coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./ingest/coverage.xml
        flags: ingest
        name: ingest-coverage
